spring:
    application:
        name: ${APP_NAME:COMMUNAL}
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:communal}
        driver-class-name: org.postgresql.Driver
        username: ${POSTGRES_DB_USER:adkhambek}
        password: ${POSTGRES_DB_PASS:12345}
    jpa:
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
        generate-ddl: true
        hibernate:
            ddl-auto: update
server:
    port: ${APP_PORT:8080}

permission:
    roles:
        -   name: ADMIN
        -   name: USER
    access:
        -   url: /api/v1/communal/**
            permit:
                -   method: GET
                    roles:
                        - ADMIN
                        - USER

        -   url: /api/v1/category/**
            permit:
                -   method: GET
                    roles:
                        - ADMIN
                        - USER

management:
    endpoints:
        web:
            exposure:
                include: prometheus,health,info,metrics
    metrics:
        export:
            prometheus:
                enabled: true
        distribution:
            percentiles-histogram:
                "[http.server.requests]": true