version: "3"

services:

  postgresql:
    restart: always
    build: postgres/
    container_name: postgresql
    environment:
      TZ: Asia/Tashkent
      POSTGRES_DB: communal-new
      POSTGRES_USER: adkhambek
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      monitoring:
        aliases:
          - postgresql

  http_app:
    container_name: communal
    build: app/
    environment:
      JAVA_OPTS:
        -DAPP_NAME=communal
        -DAPP_PORT=8080
        -DPOSTGRES_HOST=postgresql
        -DPOSTGRES_PORT=5432
        -DPOSTGRES_DB_NAME=communal-new
        -DPOSTGRES_DB_USER=adkhambek
        -DPOSTGRES_DB_PASS=12345
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      monitoring:
        aliases:
          - http_app

  app_ui:
    container_name: communal-ui
    build: ui/
    ports:
      - 8081:8080
    depends_on:
      - http_app
    networks:
      monitoring:
        aliases:
          - app_ui

  grafana:
    build: './config/grafana'
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus

networks:
  monitoring:
    